/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidorsd;

import io.atomix.catalyst.transport.Address;
import io.atomix.copycat.client.CopycatClient;
import io.atomix.copycat.server.CopycatServer;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import javax.swing.event.ChangeEvent;
import raft.PutCommand;
import raft.RaftServer;
import shared.Aresta;
import shared.Grafo;
import shared.Vertice;

/**
 *
 * @author ThiagoH
 */
public class ServerUI extends javax.swing.JFrame {

    private ServidorSD[] server; //servidores thrift
    private CopycatServer[] serversRaft; //servidores raft
    
    Collection<Address> cluster; //conjunto de servidores raft
    int idCluster;
    public ServerUI() {
        initComponents();
        
        idCluster = 0;
        cluster = new ArrayList<>();
        serversRaft = new CopycatServer[3];
        
        server = new ServidorSD[3];
        server[0] = new ServidorSD();
        server[1] = new ServidorSD();
        server[2] = new ServidorSD();
    }
    
    public static void main(String[] args)
    {
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerUI().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtStatusServer = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnLigar = new javax.swing.JButton();
        btnSetar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtServidor1 = new javax.swing.JTextField();
        txtPorta1 = new javax.swing.JTextField();
        txtPorta2 = new javax.swing.JTextField();
        txtServidor2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPorta3 = new javax.swing.JTextField();
        txtServidor3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPortaCopyCat1 = new javax.swing.JTextField();
        txtPortaCopyCat2 = new javax.swing.JTextField();
        txtPortaCopyCat3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdCluster = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GrafoDB Server");

        txtStatusServer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtStatusServer.setForeground(new java.awt.Color(204, 51, 0));
        txtStatusServer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStatusServer.setText("Server não iniciado.");

        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setText("DESLIGAR");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLigar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnLigar.setText("LIGAR");
        btnLigar.setToolTipText("");
        btnLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigarActionPerformed(evt);
            }
        });

        btnSetar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnSetar.setText("SETAR");
        btnSetar.setToolTipText("");
        btnSetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AVISO: Clique em setar antes de ligar o servidor.");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Informações do cluster:");

        jLabel6.setText("Endereço Servidor 1:");

        txtServidor1.setText("localhost");

        txtPorta1.setText("9000");
        txtPorta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorta1ActionPerformed(evt);
            }
        });

        txtPorta2.setText("9001");
        txtPorta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorta2ActionPerformed(evt);
            }
        });

        txtServidor2.setText("localhost");

        jLabel9.setText("Endereço Servidor 2:");

        txtPorta3.setText("9002");
        txtPorta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorta3ActionPerformed(evt);
            }
        });

        txtServidor3.setText("localhost");

        jLabel11.setText("Endereço Servidor 3:");

        txtPortaCopyCat1.setText("8000");
        txtPortaCopyCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortaCopyCat1ActionPerformed(evt);
            }
        });

        txtPortaCopyCat2.setText("8001");
        txtPortaCopyCat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortaCopyCat2ActionPerformed(evt);
            }
        });

        txtPortaCopyCat3.setText("8002");
        txtPortaCopyCat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortaCopyCat3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Porta GrafoDB");

        jLabel4.setText("Porta CopyCat");

        jLabel7.setText("ID do cluster:");

        txtIdCluster.setText("0");
        txtIdCluster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClusterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addComponent(txtStatusServer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPortaCopyCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtServidor2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtPorta2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtServidor3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtPorta3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtServidor1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtPorta1)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(txtPortaCopyCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtPortaCopyCat3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(btnLigar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSetar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIdCluster, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(txtStatusServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtServidor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPortaCopyCat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtServidor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPortaCopyCat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtServidor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPortaCopyCat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCluster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetar)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLigar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        serversRaft[0].shutdown();
        serversRaft[1].shutdown();
        serversRaft[2].shutdown();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigarActionPerformed
        // TODO add your handling code here:

        System.out.println("Ligando servidores...");
    
        serversRaft[0] = RaftServer.criaServer(cluster, txtServidor1.getText(), Integer.parseInt(txtPortaCopyCat1.getText()));
        serversRaft[1] = RaftServer.adicionaServer(cluster, txtServidor2.getText(), Integer.parseInt(txtPortaCopyCat2.getText()));
        serversRaft[2] = RaftServer.adicionaServer(cluster, txtServidor3.getText(), Integer.parseInt(txtPortaCopyCat3.getText()));

        CopycatClient c2 = RaftServer.iniciaCliente(cluster);
        CopycatClient c1 = RaftServer.iniciaCliente(cluster);
        
        
        
       
        
        //c2.<ChangeEvent>onEvent("change", event -> System.out.println("CLASSE: " + event.getClass()));
        
        c2.onEvent("put", event -> {
                System.out.println("PUT!!!");
        });
        
 
        System.out.println("ANTES COMANDO.");
        c1.submit(new PutCommand("inserir", 12));
        c1.submit(new PutCommand("inserir", 13));
        
        //server[0].IniciaServer();
        //server[1].IniciaServer();
        //server[2].IniciaServer();
        txtStatusServer.setText("Servidores iniciados.");
        txtStatusServer.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnLigarActionPerformed

    private void btnSetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetarActionPerformed
         // TODO add your handling code here:
        cluster.clear();
        cluster.add(new Address(txtServidor1.getText(),Integer.parseInt(txtPortaCopyCat1.getText())));
        cluster.add(new Address(txtServidor2.getText(),Integer.parseInt(txtPortaCopyCat2.getText())));
        cluster.add(new Address(txtServidor3.getText(),Integer.parseInt(txtPortaCopyCat3.getText())));
        
        server[0].setPorta(Integer.parseInt(txtPorta1.getText()));
        server[1].setPorta(Integer.parseInt(txtPorta2.getText()));
        server[2].setPorta(Integer.parseInt(txtPorta3.getText()));
        
        idCluster = Integer.parseInt(txtIdCluster.getText());
        server[0].setId(idCluster);
        server[1].setId(idCluster);
        server[2].setId(idCluster);
    }//GEN-LAST:event_btnSetarActionPerformed

    private void txtPorta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorta1ActionPerformed

    private void txtPorta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorta2ActionPerformed

    private void txtPorta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorta3ActionPerformed

    private void txtPortaCopyCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortaCopyCat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaCopyCat1ActionPerformed

    private void txtPortaCopyCat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortaCopyCat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaCopyCat2ActionPerformed

    private void txtPortaCopyCat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortaCopyCat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaCopyCat3ActionPerformed

    private void txtIdClusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClusterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClusterActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLigar;
    private javax.swing.JButton btnSetar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtIdCluster;
    private javax.swing.JTextField txtPorta1;
    private javax.swing.JTextField txtPorta2;
    private javax.swing.JTextField txtPorta3;
    private javax.swing.JTextField txtPortaCopyCat1;
    private javax.swing.JTextField txtPortaCopyCat2;
    private javax.swing.JTextField txtPortaCopyCat3;
    private javax.swing.JTextField txtServidor1;
    private javax.swing.JTextField txtServidor2;
    private javax.swing.JTextField txtServidor3;
    private javax.swing.JLabel txtStatusServer;
    // End of variables declaration//GEN-END:variables
}
